### ISSUE TITLE
GitHub Actions / other automated CI

### ISSUE THREAD

**Issue by daxtens** [open-power/secvarctl#32]
It'd be really nice to know if a commit passes the tests before I merge it. I'm sure all our committers make only the finest pull requests and test them locally first, of course. But I for one have made a 'trivial' change to my patches and pushed, only to later find out my trivial change was not so trivial and broke something.

I think because the tests work on x86 we could run them under GH Actions without any difficulty.

**Comment by erichte-ibm** [comment]
Extending this, because it would be nice to have some form of automated builds for releases. Not sure if actions are the correct tool for this, but it would be nice to have `*.rpm`s and static builds attached to tagged releases. Ideally provide builds for both x86 and power, perhaps also using mbedtls/openssl.

**Comment by erichte-ibm** [comment]
Implemented in #35 and #56
